### ISSUE TITLE
Feature request: increment editor (motion path), implemented in Tahoma 2D (OpenToons fork)

### ISSUE THREAD

**Issue by charliemartinez** [wentasah/qstopmotion#1]
This is the motion path made by Tahoma 2D:

![Motion path](https://user-images.githubusercontent.com/19245851/158688225-ad554908-8682-46fc-a91d-eac4f47f3649.gif)

The tool works as a guide. The operation is similar to the Dragonframe "increment editor" tool:

[![Dragonframe Increment Editor demostration](https://www.fpcharlie.ga/files/increment-editor.png)](https://www.fpcharlie.ga/files/increment-editor.mp4)

 I wonder if it will be possible to adopt Tahoma's motion path in **qstopmotion**?

**Comment by wentasah** [comment]
Hi. I'm not a qstopmotion developer. This repository contain just some random fixes I needed for my system. You can contact the qstopmotion authors at https://sourceforge.net/projects/qstopmotion/support.
